stages:
  - build
  - package
  - deploy

ng-build:
  stage: build
  image: node:12
  script:
    - apt-get update && apt-get install gettext-base git -y
    - git config --global url."https://github.com".insteadOf git://github.com
    - npm ci
    - npm run-script version
    - cp src/environments/index.html src/
    - node --max_old_space_size=3072 node_modules/@angular/cli/bin/ng build --configuration=ci
    - export BUILD_DATE=`date --iso-8601=seconds --utc`
    - envsubst '$CI_COMMIT_SHORT_SHA $CI_PIPELINE_ID $BUILD_DATE' < src/environments/config-docker.json > dist/assets/config.json
  artifacts:
    paths:
      - dist/**

docker-package:
  stage: package
  image: gcr.io/kaniko-project/executor:debug
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA --destination $CI_REGISTRY_IMAGE:`echo $CI_COMMIT_REF_NAME | tr / _`

k8s-deploy-staging:
  stage: deploy
  rules:
    - if: '$CI_COMMIT_BRANCH == "develop"'
      when: on_success
    - if: '$CI_COMMIT_BRANCH =~ /^feature/'
      when: manual
  image: google/cloud-sdk:alpine
  script:
    - gcloud components install kubectl
    - echo "$GCP_KEY" > key.json
    - gcloud auth activate-service-account --key-file key.json
    - gcloud container clusters get-credentials yaa-go-app-eu-west1 --region europe-west1 --project yaa-go --internal-ip
    - kubectl set image deployment frontend-guest frontend-guest=$CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA --namespace=yaago-staging

k8s-deploy-qa:
  stage: deploy
  rules:
    - if: '$CI_COMMIT_BRANCH =~ /^release/ || $CI_COMMIT_BRANCH =~ /^hotfix/'
      when: on_success
    - when: manual
  image: google/cloud-sdk:alpine
  script:
    - gcloud components install kubectl
    - echo "$GCP_KEY" > key.json
    - gcloud auth activate-service-account --key-file key.json
    - gcloud container clusters get-credentials yaa-go-app-eu-west1 --region europe-west1 --project yaa-go --internal-ip
    - kubectl set image deployment frontend-guest frontend-guest=$CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA --namespace=yaago-qa

k8s-deploy-demo:
  stage: deploy
  rules:
  - when: manual
  image: google/cloud-sdk:alpine
  script:
    - gcloud components install kubectl
    - echo "$GCP_KEY" > key.json
    - gcloud auth activate-service-account --key-file key.json
    - gcloud container clusters get-credentials yaa-go-app-eu-west1 --region europe-west1 --project yaa-go --internal-ip
    - kubectl set image deployment frontend-guest frontend-guest=$CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA --namespace=yaago-demo

k8s-deploy-prod:
  stage: deploy
  rules:
  - if: '$CI_COMMIT_BRANCH == "master" || $CI_COMMIT_TAG'
    when: manual
  image: google/cloud-sdk:alpine
  script:
    - gcloud components install kubectl
    - echo "$GCP_KEY" > key.json
    - gcloud auth activate-service-account --key-file key.json
    - gcloud container clusters get-credentials yaa-go-app-eu-west1 --region europe-west1 --project yaa-go --internal-ip
    - kubectl set image deployment frontend-guest frontend-guest=$CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA --namespace=yaago-prod
